###
# Split ratios of dataset
split_ratios:
  train: 0.7
  val: 0.2
  test: 0.1

###
# Training configs
train:
  batch_size: 2
  epochs: 10
  # path to save directory for model checkpoints
  save_dir: /model/checkpoints/
  # name of the model checkpoint
  save_name: model_ch_mults_6_n_blocks_1_n_layers_1_epochs_10_sum
  # path save directory for logs
  log_dir: /outputs/logs
  precision: 16
  callbacks: 
    monitor: val_loss
    # number of checks with no improvement after which training will be stopped.
    patience: 200
    # whether to stop training when the metric is at a minimum
    mode: min    
  lr: 0.0001
  accelerator: gpu

check_dataset: True

###
# Dataset configs
dataset:
  task: SR
  mode: train
  # path to the root directory of the project
  data_root: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries
  # path to the directory of the dataset
  dataset_dir: [/dataset/pristine, /dataset/cycled]
  # size of each tile of slice in dataset
  tile_size: 512
  # number of tiles in each row of slice
  tile_grid: 4

  # preprocessing configs
  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8
  # transforms configs  
  transforms_cfg:
    propability: 1.0
    RandomAffine:
      p: 0.75
      degrees: 20
      translate:
        - 0.1
        - 0.9
      scale:
        - 0.9
        - 1.1
      # shear: ()
    #RandomCrop:
    #  size: ()
    RandomHorizontalFlip:
      p: 0.5
    RandomVerticalFlip:
      p: 0.5
    RandomBrightness:
      p: 0.75
      brightness:
        - 1.1
        - 1.1
    RandomContrast:
      p: 0.75
      contrast:
        - 1.1
        - 1.1
    RandomSaturation:
      p: 0.5
      saturation:
        - 1.1
        - 1.1
    RandomHue:
      p: 0.5
      hue:
        - -0.1
        - 0.1
    #RandomMedianBlur:
    #  p: 1.0
    RandomGaussianNoise:
      p: 0.5
      mean: 0.1
      std: 0.5
    RandomGaussianBlur:
      kernel_size_range: 
        - 1
        - 3
      sigma_range:
        - 0.1
        - 1.1

###
# Model configs
model:
  model_name: SR_model
  automatic_optimization: true
  image_channels: 1
  output_channels: 1
  c_factor: 6
  ch_mults: 6
  n_blocks: 1
  n_layers: 1
  scale_factor: 2
  kernel_size: 3
  n_groups: 32
  verbose: True 

  Optimizer:
    lr: 0.0001
    optimizer: adam
    maximize: False
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-06
    weight_decay: 1.0e-03
    momentum: 0.9
    Scheduler:
      type: plateau
      mode: min
      factor: 0.1
      threshold: 0.0001
      min_lr: 1.0e-10
      patience: 8
      cooldown: 0
      monitor: val_loss

  loss_func:
    name: MSELoss
    args:
      reduction: sum


###
# Inference configs
pred:
  # path to the model checkpoint
  ckpt_path: /model/checkpoints/model_ch_mults_6_n_blocks_1_n_layers_1_epochs_10_sum.ckpt
  device: mps
  output_dir: /results/
  output_name: SR_moded_ch_6_gaussian_blur_XTM
  slice: 1
  tiff_file_index: 1
  kernel_size: 5
  # path to the train loss csv
  train_loss_csv: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries/outputs/csv/SR_model_4_train.csv
  # path to the validation loss csv
  val_loss_csv: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries/ouputs/csv/SR_model_4_val.csv
  loss_curve_name: SR_Model_4