dataset:
  task: SR
  mode: val
  data_root: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries #H:\SR_for_CT_image_of_Batteries 
  dataset_dir: /dataset/pristine #\dataset\pristine
  tile_size: 512
  tile_grid: 4

  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8

  transforms_cfg:
    propability: 0.9
    RandomAffine:
      degrees:
      - 0
      - 0
    RandomBrightness:
      brightness:
      - 1.1
      - 1.12
    RandomContrast:
      contrast:
      - 1
      - 1

    RandomGaussianNoise:
      p: 0.75
      mean: 0.0
      std: 0.5
    RandomGaussianBlur:
      kernel_size_range:
      - 1
      - 3
      sigma_range:
      - 0.1
      - 1.0
    RandomHorizontalFlip:
      p: 0.5
      p_batch: 1.0
    RandomVerticalFlip:
      p: 0.5
      p_batch: 1.0
  
  subset_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  batch_size: 4

model:
  ckp_path:  #H:\SR_for_CT_image_of_Batteries\lightning_logs\version_5\checkpoints\epoch=0-step=9280.ckpt
  