dataset:
  task: SR
  mode: val
  data_root: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries 
  dataset_dir: /dataset/pristine 
  tile_size: 512
  tile_grid: 4

  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8

  transforms_cfg:
    propability: 0.9
    RandomAffine:
      p: 0.5
      degrees:
      - 0
      - 90
      translate:
      - 0.0
      - 1.0
      scale:
      - 0.9
      - 1.0
    RandomBrightness:
      p: 0.5
      brightness:
      - 1.1
      - 1.12
    RandomContrast:
      p: 0.5
      contrast:
      - 1
      - 1

    RandomGaussianNoise:
      p: 0.5
      mean: 0.0
      std: 0.5
    RandomGaussianBlur:
      p: 0.5
      kernel_size_range:
      - 1
      - 3
      sigma_range:
      - 0.1
      - 1.0
    RandomHorizontalFlip:
      p: 0.5
    RandomVerticalFlip:
      p: 0.5

    RandomSaturation:
      p: 0.5
    RandomHue:
      p: 0.5

pred:
  batch_size: 4
  ckpt_path: /outputs/model/checkpoints/best_model.ckpt
  device: mps
  output_dir: /results/
  output_name: pred_mean

model:
  model_name: SR_model
  automatic_optimization: true
  image_channels: 1
  output_channels: 1
  c_factor: 6
  ch_mults: 6
  n_blocks: 1
  n_layers: 1
  scale_factor: 2
  kernel_size: 3
  n_groups: 32
  verbose: true
  Optimizer:
    lr: 0.001
    optimizer: adamw
    maximize: false
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-06
    weight_decay: 0.001
    momentum: 0.9
    Scheduler:
      type: plateau
      mode: min
      factor: 0.1
      threshold: 0.0001
      min_lr: 1.0e-10
      patience: 8
      cooldown: 0
      monitor: val_loss
  loss_func:
    name: MSELoss
    args:
      reduction: sum

length: 10