# train.yaml

# General training parameters

epochs: 100

train_params:
  
  batch_size: 2

check_dataset: False

dataset:
  task: SR
  mode: train
  data_root: /home/tte/PycharmProjects/students/haorui/SR_for_CT_image_of_Batteries
  dataset_dir: /dataset/pristine
  tile_size: 128
  tile_grid: 2

  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8