# train.yaml

# General training parameters

train_params:
  max_epochs: 100
  batch_size: 4

# Data parameters

data_params:
  data_root: H:\SR_for_CT_image_of_Batteries
  dataset_dir: \dataset\pristine

  tile_size: 512
  tile_grid: 4
