# train.yaml

# General training parameters

epochs: 100

train_params:
  
  batch_size: 4

check_dataset: False # True

dataset:
  task: SR
  mode: train
  data_root: /home/tte/PycharmProjects/students/haorui/SR_for_CT_image_of_Batteries
  dataset_dir: /dataset/pristine
  tile_size: 512
  tile_grid: 4

  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8

  transforms_cfg:
    propability: 1.0
    RandomAffine:
      p: 0.5
      degrees: 90
      translate:
        - 0.0
        - 1.0
      scale:
        - 0.9
        - 1.1
      # shear: ()
    #RandomCrop:
    #  size: ()
    RandomHorizontalFlip:
      p: 0.5
    RandomVerticalFlip:
      p: 0.5
    RandomBrightness:
      p: 0.5
      brightness:
        - 0.9
        - 1.1
    RandomContrast:
      p: 0.5
      contrast:
        - 0.9
        - 1.1
    RandomSaturation:
      p: 0.5
      saturation:
        - 0.9
        - 1.1
    RandomHue:
      p: 0.5
      hue:
       - -0.1
       - 0.1
    #RandomMedianBlur:
    #  p: 1.0
    RandomGaussianNoise:
      p: 1.0
      mean: 0.0
      std: 0.1