# train.yaml

# General training parameters

train_params:
  
  batch_size: 4


dataset:
  task: SR
  mode: train
  data_root: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries 
  dataset_dir: /dataset/pristine
  tile_size: 512
  tile_grid: 4

  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8