# train.yaml

# General training parameters

epochs: 1

train_params:
  
  batch_size: 2

check_dataset: False

dataset:
  task: SR
  mode: train
  data_root: /Users/haoruilong/BA_code/SR_for_CT_image_of_Batteries
  dataset_dir: /dataset/pristine
  tile_size: 512
  tile_grid: 4

  preprocess_cfg:
    convert_dtype: null
    binning:
      binning_factor: 8

  transforms_cfg:
    propability: 0.9
    RandomAffine:
      degrees:
      - 0
      - 0
    RandomBrightness:
      brightness:
      - 1.1
      - 1.12
    RandomContrast:
      contrast:
      - 1
      - 1

    RandomGaussianNoise:
      p: 0.75
      mean: 0.0
      std: 0.5
    RandomGaussianBlur:
      kernel_size_range:
      - 1
      - 3
      sigma_range:
      - 0.1
      - 1.0
    RandomHorizontalFlip:
      p: 0.5
      p_batch: 1.0
    RandomVerticalFlip:
      p: 0.5
      p_batch: 1.0