propability: 1.0
RandomAffine:
  p: 0.5
  degrees: 90
  translate: (0.0, 1.0)
  scale: (0.9, 1.1)
  # shear: ()
#RandomCrop:
#  size: ()
RandomHorizontalFlip:
  p: 0.5
RandomVerticalFlip:
  p: 0.5
RandomBrightness:
  p: 0.5
RandomContrast:
  p: 0.5
RandomSaturation:
  p: 0.5
RandomHue:
  p: 0.5
#RandomMedianBlur:
#  p: 1.0
RandomGaussianNoise:
  p: 0.75
  mean: 0.0
  std: 0.5
RandomGaussianBlur:
  p: 0.25
  kernel_size_range: (1, 3)
  sigma_range: (0.1, 1.0)
RandomDropoff:
  p: 0.25
  prob: 0.5
RandomSaltAndPepper:
  p: 0.25
  salt_prob: 0.2
  pepper_prob: 0.2